apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: minesweeper-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: gitsecret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: minesweeper-trigger-binding
  template:
    ref: minesweeper-trigger-template